services:

  # Proxy server
  caddy:
    image: caddy:latest
    container_name: '${CONTAINER_NAME}-caddy'
    depends_on:
      - app
    networks:
      - app-network
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - '../../:/var/www'
      - '../Caddyfile:/etc/caddy/Caddyfile'
