services:

  # Nginx server
  nginx:
    restart: '${RESTART_POLICY}'
    container_name: '${CONTAINER_NAME}-nginx'
    image: nginx:latest
    ports:
      - '${APP_PORT}:80'
    volumes:
      - '../nginx.conf:/etc/nginx/conf.d/default.conf'
      - '../../:/var/www/${CONTAINER_NAME}'
      - '${STORAGE_MOUNT_PATH:-./storage}:/var/www/${CONTAINER_NAME}/storage'
    depends_on:
      - app
    networks:
      - app-network
