services:
  mailpit:
    image: axllent/mailpit
    container_name: ${CONTAINER_NAME}-mailpit
    restart: '${RESTART_POLICY}'
    networks:
      - app-network
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 100
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mailpit:
    driver: local
