services:

  # App
  app:
    ports:
      - '${APP_PORT:-8000}:80'

  # MariaDB
  mariadb:
    ports:
      # Expose the port 3306 to the host
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'

volumes:
  mariadb:
    driver: local